const data = {
  products: [
    {
      // _id: "1",
      slug: " nike shirt 1",
      name: "nike shirt 1",
      Category: "shirt",
      image: "/images/form10.jpg",
      price: "100",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
      countInStock: 3,
    },
    {
      // _id: "2",
      slug: " nike shirt 2",
      name: "nike shirt 2",
      Category: "shirt",
      image: "/images/form10.jpg",
      price: "100",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
      countInStock: 5,
    },
    {
      // _id: "3",
      slug: " nike shirt 3",
      name: "nike shirt 3",
      Category: "shirt",
      image: "/images/form10.jpg",
      price: "100",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
      countInStock: 5,
    },
    {
      // _id: "4",
      slug: " nike shirt 4",
      name: "nike shirt 4",
      Category: "shirt",
      image: "/images/form10.jpg",
      countInStock: 5,
      price: "100",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
      countInStock: 5,
    },
  ],
};

export default data;
